services:
  db:
    image: mariadb:latest
    restart: always
    container_name: sre-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_USER_PWD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_HOST: db
      DATABASE_HOST: db

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: sre-app
    env_file:
      - .env
    environment:
        DATABASE_HOST: db
        ENVIRONMENT: docker
    ports:
      - "8000:8000"
    image: fastapi:latest
    depends_on:
      - db
    command: [ "sh", "-c", "sleep 5 && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000" ]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: sre-nginx
    ports:
      - "80:80"
    depends_on:
      - app
