apiVersion: batch/v1
kind: Job
metadata:
  name: sre-alembic-migration
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      containers:
      - name: alembic
        image: dhanasekars/alembic_migrations:main
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_NAME
        command: ["sh", "-c", "sleep 5 && alembic upgrade head"]
      restartPolicy: OnFailure
      initContainers:
            - name: wait-for-mariadb
              image: busybox
              command: ['sh', '-c', 'until nc -z $(DATABASE_HOST) 3306; do echo "Waiting for MariaDB..."; sleep 5; done;']
              env:
              - name: DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: DATABASE_HOST

  backoffLimit: 3
