apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-mariadb
  template:
    metadata:
      labels:
        app: sre-mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m03
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_ROOT_USER_PWD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_NAME
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 3306  # MariaDB default port

      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
