# Use the previously built image as the base image
FROM dhanasekars/fastapi_app:main AS base

# Set the working directory
WORKDIR /app

# Copy the Alembic configuration and migration scripts
COPY ./alembic ./alembic
COPY ./alembic.ini .