name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create Build Directory
        run:  mkdir -p /Users/dhanasekarsubramaniam/actions-runner/_work

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8  # Ensure flake8 is installed
          # Run flake8 with desired configuration
          flake8 .
#        continue-on-error: false  # Fail the pipeline if linting fails

      - name: Run Tests
        run: |
          pytest
